// <auto-generated />
using System;
using IdentityRiskAnalyzer.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityRiskAnalyzer.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924064717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.AdObjectSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AccountExpired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServiceAccount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastKnownActivityUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PasswordLastSetUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PasswordNeverExpires")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SamAccountName")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sid")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrincipalName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectGuid");

                    b.HasIndex("ScanRunId", "ObjectGuid");

                    b.ToTable("AdObjectSnapshots");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.DelegationRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DelegationType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.ToTable("DelegationRecords");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.GroupMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupDistinguishedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId", "PrincipalObjectGuid");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.RiskFinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectGuid");

                    b.HasIndex("RuleId");

                    b.HasIndex("ScanRunId");

                    b.ToTable("RiskFindings");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.ScanRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdSecurityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FindingsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectsScanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.AdObjectSnapshot", b =>
                {
                    b.HasOne("IdentityRiskAnalyzer.Web.Domain.Entities.ScanRun", "ScanRun")
                        .WithMany("AdObjectSnapshots")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.DelegationRecord", b =>
                {
                    b.HasOne("IdentityRiskAnalyzer.Web.Domain.Entities.ScanRun", "ScanRun")
                        .WithMany("DelegationRecords")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.GroupMembership", b =>
                {
                    b.HasOne("IdentityRiskAnalyzer.Web.Domain.Entities.ScanRun", "ScanRun")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.RiskFinding", b =>
                {
                    b.HasOne("IdentityRiskAnalyzer.Web.Domain.Entities.ScanRun", "ScanRun")
                        .WithMany("RiskFindings")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("IdentityRiskAnalyzer.Web.Domain.Entities.ScanRun", b =>
                {
                    b.Navigation("AdObjectSnapshots");

                    b.Navigation("DelegationRecords");

                    b.Navigation("GroupMemberships");

                    b.Navigation("RiskFindings");
                });
#pragma warning restore 612, 618
        }
    }
}
